language: php
php:
  - 5.5
  - 5.6
before_script:
  - composer self-update
  - composer install --no-interaction --prefer-dist
script:
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_script:
  - php vendor/bin/coveralls
